[package]
name = "atlast"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png="*"
walkdir="2"
clap="2"
serde = { version="*", features = ["derive"] }
bincode = "1.3"
zip = "*"
